/* mds.h
   Generated by wsdl2h 2.8.21 from http://10.240.129.168:9999/HBDRM/services/SGCMSwitchProject?wsdl and typemap.dat
   2016-04-25 03:11:00 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2014 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on mds.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://main.sgcm.com                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://main.sgcm.com"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://main.sgcm.com"
//gsoap ns1   schema namespace:	http://main.sgcm.com
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _ns1__getSampleInfo.
class _ns1__getSampleInfo;

//  Forward declaration of class _ns1__getSampleInfoResponse.
class _ns1__getSampleInfoResponse;

//  Forward declaration of class _ns1__sendProjectResults.
class _ns1__sendProjectResults;

//  Forward declaration of class _ns1__sendProjectResultsResponse.
class _ns1__sendProjectResultsResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://main.sgcm.com                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://main.sgcm.com                                                     *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://main.sgcm.com":getSampleInfo
/// @brief "http://main.sgcm.com":getSampleInfo is a complexType.
///
/// class _ns1__getSampleInfo operations:
/// - soap_new__ns1__getSampleInfo(soap*) allocate
/// - soap_new__ns1__getSampleInfo(soap*, int num) allocate array
/// - soap_new_req__ns1__getSampleInfo(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__getSampleInfo(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__getSampleInfo(soap*, _ns1__getSampleInfo*) deserialize from a stream
/// - int soap_write__ns1__getSampleInfo(soap, _ns1__getSampleInfo*) serialize to a stream
class _ns1__getSampleInfo
{ public:
/// Element "sampleNo" of XSD type xs:string.
    std::string                          sampleNo                       1;	///< Required element.
/// Element "sysParams" of XSD type xs:string.
    std::string                          sysParams                      1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://main.sgcm.com":getSampleInfoResponse
/// @brief "http://main.sgcm.com":getSampleInfoResponse is a complexType.
///
/// class _ns1__getSampleInfoResponse operations:
/// - soap_new__ns1__getSampleInfoResponse(soap*) allocate
/// - soap_new__ns1__getSampleInfoResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__getSampleInfoResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__getSampleInfoResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__getSampleInfoResponse(soap*, _ns1__getSampleInfoResponse*) deserialize from a stream
/// - int soap_write__ns1__getSampleInfoResponse(soap, _ns1__getSampleInfoResponse*) serialize to a stream
class _ns1__getSampleInfoResponse
{ public:
/// Element "getSampleInfoReturn" of XSD type xs:string.
    std::string                          getSampleInfoReturn            1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://main.sgcm.com":sendProjectResults
/// @brief "http://main.sgcm.com":sendProjectResults is a complexType.
///
/// class _ns1__sendProjectResults operations:
/// - soap_new__ns1__sendProjectResults(soap*) allocate
/// - soap_new__ns1__sendProjectResults(soap*, int num) allocate array
/// - soap_new_req__ns1__sendProjectResults(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__sendProjectResults(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__sendProjectResults(soap*, _ns1__sendProjectResults*) deserialize from a stream
/// - int soap_write__ns1__sendProjectResults(soap, _ns1__sendProjectResults*) serialize to a stream
class _ns1__sendProjectResults
{ public:
/// Element "sampleNo" of XSD type xs:string.
    std::string                          sampleNo                       1;	///< Required element.
/// Element "sysParams" of XSD type xs:string.
    std::string                          sysParams                      1;	///< Required element.
/// Element "checkResult" of XSD type xs:string.
    std::string                          checkResult                    1;	///< Required element.
/// Element "checkDate" of XSD type xs:string.
    std::string                          checkDate                      1;	///< Required element.
/// Element "testMan" of XSD type xs:string.
    std::string                          testMan                        1;	///< Required element.
/// Element "checkMan" of XSD type xs:string.
    std::string                          checkMan                       1;	///< Required element.
/// Element "checkTemp" of XSD type xs:string.
    std::string                          checkTemp                      1;	///< Required element.
/// Element "checkWet" of XSD type xs:string.
    std::string                          checkWet                       1;	///< Required element.
/// Element "projects" of XSD type xs:string.
    std::string                          projects                       1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://main.sgcm.com":sendProjectResultsResponse
/// @brief "http://main.sgcm.com":sendProjectResultsResponse is a complexType.
///
/// class _ns1__sendProjectResultsResponse operations:
/// - soap_new__ns1__sendProjectResultsResponse(soap*) allocate
/// - soap_new__ns1__sendProjectResultsResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__sendProjectResultsResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__sendProjectResultsResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__sendProjectResultsResponse(soap*, _ns1__sendProjectResultsResponse*) deserialize from a stream
/// - int soap_write__ns1__sendProjectResultsResponse(soap, _ns1__sendProjectResultsResponse*) serialize to a stream
class _ns1__sendProjectResultsResponse
{ public:
/// Element "sendProjectResultsReturn" of XSD type xs:string.
    std::string                          sendProjectResultsReturn       1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://main.sgcm.com                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://main.sgcm.com                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	SGCMSwitchProjectSoapBinding 
//gsoap ns1  service type:	SGCMSwitchProject 
//gsoap ns1  service port:	http://10.240.129.168:9999/HBDRM/services/SGCMSwitchProject 
//gsoap ns1  service namespace:	http://main.sgcm.com 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref SGCMSwitchProjectSoapBinding

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page SGCMSwitchProjectSoapBinding Binding "SGCMSwitchProjectSoapBinding"

@section SGCMSwitchProjectSoapBinding_operations Operations of Binding "SGCMSwitchProjectSoapBinding"

  - @ref __ns1__getSampleInfo

  - @ref __ns1__sendProjectResults

@section SGCMSwitchProjectSoapBinding_ports Endpoints of Binding "SGCMSwitchProjectSoapBinding"

  - http://10.240.129.168:9999/HBDRM/services/SGCMSwitchProject

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   SGCMSwitchProjectSoapBinding                                             *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getSampleInfo                                                     *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getSampleInfo" of service binding "SGCMSwitchProjectSoapBinding".

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getSampleInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getSampleInfo*                ns1__getSampleInfo,
    // output parameters:
    _ns1__getSampleInfoResponse        &ns1__getSampleInfoResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getSampleInfo(
    struct soap *soap,
    // input parameters:
    _ns1__getSampleInfo*                ns1__getSampleInfo,
    // output parameters:
    _ns1__getSampleInfoResponse        &ns1__getSampleInfoResponse
  );
@endcode

C++ proxy class (defined in soapSGCMSwitchProjectSoapBindingProxy.h):
@code
  class SGCMSwitchProjectSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapSGCMSwitchProjectSoapBindingService.h):
@code
  class SGCMSwitchProjectSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getSampleInfo SOAP
//gsoap ns1  service method-style:	getSampleInfo document
//gsoap ns1  service method-encoding:	getSampleInfo literal
//gsoap ns1  service method-action:	getSampleInfo ""
//gsoap ns1  service method-output-action:	getSampleInfo Response
int __ns1__getSampleInfo(
    _ns1__getSampleInfo*                ns1__getSampleInfo,	///< Input parameter
    _ns1__getSampleInfoResponse        &ns1__getSampleInfoResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__sendProjectResults                                                *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__sendProjectResults" of service binding "SGCMSwitchProjectSoapBinding".

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__sendProjectResults(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__sendProjectResults*           ns1__sendProjectResults,
    // output parameters:
    _ns1__sendProjectResultsResponse   &ns1__sendProjectResultsResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__sendProjectResults(
    struct soap *soap,
    // input parameters:
    _ns1__sendProjectResults*           ns1__sendProjectResults,
    // output parameters:
    _ns1__sendProjectResultsResponse   &ns1__sendProjectResultsResponse
  );
@endcode

C++ proxy class (defined in soapSGCMSwitchProjectSoapBindingProxy.h):
@code
  class SGCMSwitchProjectSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapSGCMSwitchProjectSoapBindingService.h):
@code
  class SGCMSwitchProjectSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	sendProjectResults SOAP
//gsoap ns1  service method-style:	sendProjectResults document
//gsoap ns1  service method-encoding:	sendProjectResults literal
//gsoap ns1  service method-action:	sendProjectResults ""
//gsoap ns1  service method-output-action:	sendProjectResults Response
int __ns1__sendProjectResults(
    _ns1__sendProjectResults*           ns1__sendProjectResults,	///< Input parameter
    _ns1__sendProjectResultsResponse   &ns1__sendProjectResultsResponse	///< Output parameter
);

/**

@page SGCMSwitchProjectSoapBinding Binding "SGCMSwitchProjectSoapBinding"

@section SGCMSwitchProjectSoapBinding_policy_enablers Policy Enablers of Binding "SGCMSwitchProjectSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://main.sgcm.com"

  - <getSampleInfo> @ref _ns1__getSampleInfo
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSampleInfo(struct soap*, _ns1__getSampleInfo*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSampleInfo(struct soap*, _ns1__getSampleInfo*);
    @endcode

  - <getSampleInfoResponse> @ref _ns1__getSampleInfoResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getSampleInfoResponse(struct soap*, _ns1__getSampleInfoResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getSampleInfoResponse(struct soap*, _ns1__getSampleInfoResponse*);
    @endcode

  - <sendProjectResults> @ref _ns1__sendProjectResults
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__sendProjectResults(struct soap*, _ns1__sendProjectResults*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__sendProjectResults(struct soap*, _ns1__sendProjectResults*);
    @endcode

  - <sendProjectResultsResponse> @ref _ns1__sendProjectResultsResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__sendProjectResultsResponse(struct soap*, _ns1__sendProjectResultsResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__sendProjectResultsResponse(struct soap*, _ns1__sendProjectResultsResponse*);
    @endcode

*/

/* End of mds.h */
