/* soapSGCMSwitchProjectSoapBindingProxy.h
   Generated by gSOAP 2.8.21 from mds.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapSGCMSwitchProjectSoapBindingProxy_H
#define soapSGCMSwitchProjectSoapBindingProxy_H
#include "soapH.h"

class SOAP_CMAC SGCMSwitchProjectSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'SGCMSwitchProjectSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in mds.h (non-static)
	/// Constructor
	SGCMSwitchProjectSoapBindingProxy();
	/// Construct from another engine state
	SGCMSwitchProjectSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	SGCMSwitchProjectSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	SGCMSwitchProjectSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	SGCMSwitchProjectSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	SGCMSwitchProjectSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~SGCMSwitchProjectSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void SGCMSwitchProjectSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getSampleInfo' (returns error code or SOAP_OK)
	virtual	int getSampleInfo(_ns1__getSampleInfo *ns1__getSampleInfo, _ns1__getSampleInfoResponse &ns1__getSampleInfoResponse) { return this->getSampleInfo(NULL, NULL, ns1__getSampleInfo, ns1__getSampleInfoResponse); }
	virtual	int getSampleInfo(const char *endpoint, const char *soap_action, _ns1__getSampleInfo *ns1__getSampleInfo, _ns1__getSampleInfoResponse &ns1__getSampleInfoResponse);

	/// Web service operation 'sendProjectResults' (returns error code or SOAP_OK)
	virtual	int sendProjectResults(_ns1__sendProjectResults *ns1__sendProjectResults, _ns1__sendProjectResultsResponse &ns1__sendProjectResultsResponse) { return this->sendProjectResults(NULL, NULL, ns1__sendProjectResults, ns1__sendProjectResultsResponse); }
	virtual	int sendProjectResults(const char *endpoint, const char *soap_action, _ns1__sendProjectResults *ns1__sendProjectResults, _ns1__sendProjectResultsResponse &ns1__sendProjectResultsResponse);
};
#endif
