/* soapSGCMSwitchProjectSoapBindingProxy.cpp
   Generated by gSOAP 2.8.21 from mds.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapSGCMSwitchProjectSoapBindingProxy.h"

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy()
{	SGCMSwitchProjectSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy(const char *url)
{	SGCMSwitchProjectSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy(soap_mode iomode)
{	SGCMSwitchProjectSoapBindingProxy_init(iomode, iomode);
}

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy(const char *url, soap_mode iomode)
{	SGCMSwitchProjectSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy(soap_mode imode, soap_mode omode)
{	SGCMSwitchProjectSoapBindingProxy_init(imode, omode);
}

SGCMSwitchProjectSoapBindingProxy::~SGCMSwitchProjectSoapBindingProxy()
{ }

void SGCMSwitchProjectSoapBindingProxy::SGCMSwitchProjectSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://main.sgcm.com", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void SGCMSwitchProjectSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void SGCMSwitchProjectSoapBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	SGCMSwitchProjectSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void SGCMSwitchProjectSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *SGCMSwitchProjectSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *SGCMSwitchProjectSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *SGCMSwitchProjectSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *SGCMSwitchProjectSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int SGCMSwitchProjectSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int SGCMSwitchProjectSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void SGCMSwitchProjectSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void SGCMSwitchProjectSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *SGCMSwitchProjectSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int SGCMSwitchProjectSoapBindingProxy::getSampleInfo(const char *endpoint, const char *soap_action, _ns1__getSampleInfo *ns1__getSampleInfo, _ns1__getSampleInfoResponse &ns1__getSampleInfoResponse)
{	struct soap *soap = this;
	struct __ns1__getSampleInfo soap_tmp___ns1__getSampleInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.240.129.168:9999/HBDRM/services/SGCMSwitchProject";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSampleInfo.ns1__getSampleInfo = ns1__getSampleInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__getSampleInfo(soap, &soap_tmp___ns1__getSampleInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSampleInfo(soap, &soap_tmp___ns1__getSampleInfo, "-ns1:getSampleInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSampleInfo(soap, &soap_tmp___ns1__getSampleInfo, "-ns1:getSampleInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__getSampleInfoResponse)
		return soap_closesock(soap);
	ns1__getSampleInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSampleInfoResponse.soap_get(soap, "ns1:getSampleInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int SGCMSwitchProjectSoapBindingProxy::sendProjectResults(const char *endpoint, const char *soap_action, _ns1__sendProjectResults *ns1__sendProjectResults, _ns1__sendProjectResultsResponse &ns1__sendProjectResultsResponse)
{	struct soap *soap = this;
	struct __ns1__sendProjectResults soap_tmp___ns1__sendProjectResults;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.240.129.168:9999/HBDRM/services/SGCMSwitchProject";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__sendProjectResults.ns1__sendProjectResults = ns1__sendProjectResults;
	soap_serializeheader(soap);
	soap_serialize___ns1__sendProjectResults(soap, &soap_tmp___ns1__sendProjectResults);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__sendProjectResults(soap, &soap_tmp___ns1__sendProjectResults, "-ns1:sendProjectResults", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__sendProjectResults(soap, &soap_tmp___ns1__sendProjectResults, "-ns1:sendProjectResults", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&ns1__sendProjectResultsResponse)
		return soap_closesock(soap);
	ns1__sendProjectResultsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__sendProjectResultsResponse.soap_get(soap, "ns1:sendProjectResultsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
