#if 0
#include "mainwindow.h"
#include "ui_mainwindow.h"
#include"QDebug"
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QObject>
#include "unistd.h"
#include "QSqlError"

void MainWindow::on_localSql_insert_PsBtn_clicked()
{


//strExec = "CREATE TABLE  MT_DETECT_RSLT( Num  integer primary key autoincrement    char(8),DETECT_TASK_NO char(8),EQUIP_CATEG char(8),SYS_NO char(8),DETECT_EQUIP_NO char(8),DETECT_UNIT_NO char(8),POSITION_NO char(8),BAR_CODE char(8),DETECT_DATE char(8),CONC_CODE char(8),INTUIT_CONC_CODE char(8),BASICERR_CONC_CODE char(8),CONST_CONC_CODE char(8),STARTING_CONC_CODE char(8),CREEPING_CONC_CODE char(8),DAYERR_CONC_CODE char(8),POWER_CONC_CODE char(8),VOLT_CONC_CODE char(8),STANDARD_CONC_CODE char(8),WAVE_CONC_CODE char(8),ERROR_CONC_CODE char(8),CONSIST_CONC_CODE char(8),VARIATION_CONC_CODE char(8),OVERLOAD_CONC_CODE char(8),TS_CONC_CODE char(8),RUNING_CONC_CODE char(8),PERIOD_CONC_CODE char(8),VALUE_CONC_CODE char(8),KEY_CONC_CODE char(8),ESAM_CONC_CODE char(8),REMOTE_CONC_CODE char(8),EH_CONC_CODE char(8),EC_CONC_CODE char(8),SWITCH_ON_CONC_CODE char(8),SWITCH_OUT_CONC_CODE char(8),WARN_CONC_CODE char(8),WARN_CANCEL_CONC_CODE char(8),SURPLUS_CONC_CODE char(8),RESET_EQ_MET_CONC_CODE char(8),INFRARED_TEST_CONC_CODE char(8),RESET_DEMAND_MET_CONC_CODE char(8),TIMING_MET_CONC_CODE char(8),COMMINICATE_MET_CONC_CODE char(8),ADDRESS_MET_CONC_CODE char(8),MULTI_INTERFACE_MET_CONC_CODE char(8),LEAP_YEAR_MET_CONC char(8),PARA_READ_MET_CONC_CODE char(8),PARA_SET_MET_CONC char(8),SETTING_CONC_CODE char(8),DEVIATION_MET_CONC char(8),GPS_CONC char(8),DETECT_PERSON char(8),AUDIT_PERSON char(8),WRITE_DATE char(8),SEAL_HANDLE_FLAG char(8),SEAL_HANDLE_DATE char(8),HANDLE_FLAG char(8),HANDLE_DATE char(8),TEMP char(8),HUMIDITY char(8),PRESET_PARAMET_CHECK_CONC_CODE char(8),PASSWORD_CHANGE_CONC_CODE char(8),PRESET_PARAMETER_SET_CONC_CODE char(8),RELIABILITY_CONC_CODE char(8),MOVE_STABILITY_TEST_CONC_CODE char(8),ANTI_SEISMICTEST_CONC_CODE char(8),PRESET_PARAM2_CHECK_CONC_CODE char(8),PRESET_PARAM3_CHECK_CONC_CODE char(8),PRESET_PARAM2_SET_CONC_CODE char(8),PRESET_PARAM3_SET_CONC_CODE char(8),HARD_VERSION char(8),FAULT_TYPE char(8),EVENT_REC_FUNC_CONC_CODE char(8),INFLUENCE_QTY_CONC_CODE char(8),AUX_POW_CONC_CODE char(8),ALARM_FUNC_CONC_CODE char(8),RATE_TIME_FUNC_CONC_CODE char(8),ELE_ENERGY_FUNC_CONC_CODE char(8),EXPIRATION_DATE char(8),MEA_REP_CONC_CODE char(8),CERT_NO char(8),CERT_NO_PERIOD char(8),UNPASS_REASON char(8),COMM_MODE_CHG_CONC_CODE char(8),COMM_MODE_INT_CONC_CODE char(8),FROZEN_FUNC_CONC_CODE char(8));";

//strAct  = "CREATE TABLE  MT_DETECT_RSLT";


}
#endif
